# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c69907f926363adf0638982e2141e4f"
name = "extension_demo"
handle = "extension_demo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "test-get-data.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
